//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by fastcopy.rc
//
#define IDS_MKDIR                       1
#define IDS_RMDIR                       2
#define IDS_SRC_SELECT                  3
#define IDS_DST_SELECT                  4
#define IDS_SAMEDISK                    5
#define IDS_DIFFDISK                    6
#define IDS_FIX_SAMEDISK                7
#define IDS_FIX_DIFFDISK                8
#define IDS_ALLSKIP                     20
#define IDS_ATTRCMP                     21
#define IDS_UPDATECOPY                  22
#define IDS_FORCECOPY                   23
#define IDS_SYNCCOPY                    24
#define IDS_MUTUAL                      25
#define IDS_MOVEATTR                    26
#define IDS_MOVEFORCE                   27
#define IDS_DELETE                      28
#define IDS_EXECUTE                     29
#define IDS_CANCEL                      30
#define IDS_BEHAVIOR                    31
#define IDS_UPDATE                      32
#define IDS_FILESELECT                  33
#define IDS_DIRSELECT                   34
#define IDS_SAMEPATHERR                 41
#define IDS_PARENTPATHERR               42
#define IDS_MOVECONFIRM                 43
#define IDS_SHELLEXT_MODIFY             44
#define IDS_SHELLEXT_EXEC               45
#define IDS_FASTCOPYURL                 46
#define IDS_FASTCOPYHELP                47
#define IDS_EXCEPTIONLOG                48
#define IDS_SYNCCONFIRM                 49
#define IDS_BACKSLASHERR                50
#define IDS_ERRSTOP                     60
#define IDS_CONFIRMFORCEEND             61
#define IDS_STOPCONFIRM                 62
#define IDS_DELSTOPCONFIRM              63
#define IDS_DELCONFIRM                  64
#define IDS_DUPCONFIRM                  65
#define IDS_NOFILTER_USAGE              66
#define IDS_LISTCONFIRM                 67
#define IDS_JOBNAME                     68
#define IDS_JOBNOTFOUND                 69
#define IDS_LISTING                     70
#define IDS_REQUIRE_ADMIN               71
#define IDS_FIXPOS_MSG                  72
#define IDS_FIXSIZE_MSG                 73
#define IDS_FINACTNAME                  74
#define IDS_FINACTMENU                  75
#define IDS_FINACT_NORMAL               76
#define IDS_ELEVATE                     77
#define IDS_SHUTDOWN_MSG                78
#define IDS_HIBERNATE_MSG               79
#define IDS_SUSPEND_MSG                 80
#define IDS_FINACT_SUSPEND              81
#define IDS_FINACT_HIBERNATE            82
#define IDS_FINACT_SHUTDOWN             83
#define IDS_DATEFORMAT_MSG              84
#define IDS_SIZEFORMAT_MSG              85
#define IDS_UNDO                        100
#define IDS_CUT                         101
#define IDS_COPY                        102
#define IDS_PASTE                       103
#define IDS_DEL                         104
#define IDS_SELECTALL                   105
#define IDS_SETUP_SHEET1                106
#define IDS_SETUP_SHEET2                107
#define IDS_SETUP_SHEET3                108
#define IDS_SETUP_SHEET4                109
#define IDS_SETUP_SHEET5                110
#define IDS_SETUP_SHEET6                111
#define IDS_FACMD_ALWAYS                120
#define IDS_FACMD_NORMAL                121
#define IDS_FACMD_ERROR                 122
#define SETUP_SHEET1                    202
#define SETUP_SHEET2                    203
#define SETUP_SHEET3                    204
#define SETUP_SHEET4                    205
#define SETUP_SHEET5                    206
#define SETUP_SHEET6                    207
#define IDS_FASTCOPY                    1000
#define IDS_USAGE                       1001
#define IDS_CMD_NOEXIST_ONLY            1080
#define IDS_CMD_DIFF                    1081
#define IDS_CMD_UPDATE                  1082
#define IDS_CMD_FORCE_COPY              1083
#define IDS_CMD_SYNC                    1084
#define IDS_CMD_MUTUAL                  1085
#define IDS_CMD_MOVE                    1086
#define IDS_CMD_DELETE                  1087
#define IDS_CMD_OPT                     1088
#define IDS_CMD_MOVEATTR                1089
#define IDS_BUFSIZE_OPT                 1090
#define IDS_ERRSTOP_OPT                 1091
#define IDS_OPENWIN_OPT                 1092
#define IDS_AUTOCLOSE_OPT               1093
#define IDS_FORCECLOSE_OPT              1094
#define IDS_NOEXEC_OPT                  1095
#define IDS_NOCONFIRMDEL_OPT            1096
#define IDS_LOG_OPT                     1097
#define IDS_TO_OPT                      1098
#define IDS_ESTIMATE_OPT                1099
#define IDS_JOB_OPT                     1100
#define IDS_AUTOSLOW_OPT                1101
#define IDS_SPEED_OPT                   1102
#define IDS_UTF8LOG_OPT                 1103
#define IDS_ALLFILES_FILTER             1104
#define IDS_SHEXT1_OPT                  1111
#define IDS_SHEXT2_OPT                  1112
#define IDS_SHEXT4_OPT                  1113
#define IDS_FCSHEXT1_OPT                1114
#define IDS_INCLUDE_OPT                 1115
#define IDS_EXCLUDE_OPT                 1117
#define IDS_REGEXP_OPT                  1119
#define IDS_FORCESTART_OPT              1120
#define IDS_SKIPEMPTYDIR_OPT            1121
#define IDS_DISKMODE_OPT                1122
#define IDS_DISKMODE_SAME               1123
#define IDS_DISKMODE_DIFF               1124
#define IDS_DISKMODE_AUTO               1125
#define IDS_ACL_OPT                     1126
#define IDS_STREAM_OPT                  1127
#define IDS_OWDEL_OPT                   1128
#define IDS_SPEED_FULL                  1129
#define IDS_SPEED_AUTOSLOW              1130
#define IDS_SPEED_SUSPEND               1131
#define IDS_REPARSE_OPT                 1132
#define IDS_RUNAS_OPT                   1133
#define IDS_USERDIR_MENU                1134
#define IDS_LOGFILE_OPT                 1135
#define IDS_NOCONFIRMSTOP_OPT           1136
#define IDS_VERIFY_OPT                  1137
#define IDS_USEROLDDIR_MENU             1138
#define IDS_WIPEDEL_OPT                 1139
#define IDS_SRCFILE_OPT                 1140
#define IDS_SRCFILEW_OPT                1141
#define IDS_FINACT_OPT                  1142
#define IDS_NOTEPAD                     1146
#define IDS_LINKDEST_OPT                1147
#define IDS_RECREATE_OPT                1148
#define IDS_FROMDATE_OPT                1149
#define IDS_TODATE_OPT                  1150
#define IDS_MINSIZE_OPT                 1151
#define IDS_MAXSIZE_OPT                 1152
#define IDS_STANDBY                     1153
#define IDS_HIBERNATE                   1154
#define IDS_SHUTDOWN                    1155
#define IDS_FILELOG_OPT                 1156
#define IDS_TRUE                        1157
#define IDS_FALSE                       1158
#define IDS_FILELOGNAME                 1159
#define IDS_FILELOG_SUBDIR              1160
#define IDS_INSTALL_OPT                 1161
#define IDS_FULLSPEED_DISP              1201
#define IDS_AUTOSLOW_DISP               1202
#define IDS_SUSPEND_DISP                1203
#define IDS_RATE_DISP                   1204
#define SETUP_LIST                      2263
#define STREAMERRLOG_CHECK              2264
#define ACLERRLOG_CHECK                 2265
#define TASKBAR_CHECK                   2266
#define SPAN1_RADIO                     2267
#define SPAN2_RADIO                     2268
#define SPAN3_RADIO                     2269
#define CMDERR_COMBO                    2270
#define MAIN_DIALOG                     2331
#define INPUT_DIALOG                    2332
#define SETUP_DIALOG                    2333
#define CONFIRM_DIALOG                  2360
#define COPYCONFIRM_DIALOG              2361
#define ABOUT_DIALOG                    2370
#define SHELLEXT_DIALOG                 2371
#define DELCONFIRM_DIALOG               2373
#define JOB_DIALOG                      2376
#define MESSAGE_DIALOG                  2379
#define FINACTION_DIALOG                2380
#define USERDIROLD_MENUITEM             2381
#define PROP_MISC                       2382
#define SRC_FILE_BUTTON                 3003
#define DST_FILE_BUTTON                 3004
#define SRC_COMBO                       3006
#define DST_COMBO                       3007
#define ERRLOG_CHECK                    3008
#define BUFSIZE_EDIT                    3009
#define HISTORY_EDIT                    3010
#define NONBUFMINNTFS_EDIT              3011
#define IGNORE_CHECK                    3012
#define INPUT_EDIT                      3013
#define FILELOG_CHECK                   3014
#define NONBUFMINFAT_EDIT               3015
#define STATUS_EDIT                     3016
#define UTF8LOG_CHECK                   3017
#define SAMEDRV_STATIC                  3019
#define PATH_EDIT                       3020
#define MODE_COMBO                      3021
#define ERR_EDIT                        3022
#define HELP_BUTTON                     3026
#define MESSAGE_EDIT                    3029
#define MESSAGE_EDIT2                   3030
#define ERR_STATIC                      3031
#define ERRSTATUS_STATIC                3032
#define URL_BUTTON                      3034
#define IDSHELLEXT_CANCEL               3040
#define DD_COPY_CHECK                   3041
#define DD_MOVE_CHECK                   3042
#define IDSHELLEXT_OK                   3043
#define AUTOCLOSE_CHECK                 3045
#define SRC_EDIT                        3046
#define TASKTRAY_CHECK                  3047
#define DST_EDIT                        3048
#define EXECCONFIRM_CHECK               3049
#define MAXTRANS_EDIT                   3050
#define TOPLEVEL_CHECK                  3051
#define LCID_CHECK                      3052
#define RIGHT_NOCONFIRM_CHECK           3053
#define DD_NOCONFIRM_CHECK              3054
#define RIGHT_COPY_CHECK                3055
#define RIGHT_DELETE_CHECK              3056
#define RIGHT_SUBMENU_CHECK             3057
#define DD_SUBMENU_CHECK                3058
#define ESTIMATE_CHECK                  3059
#define SAMEDIR_RENAME_CHECK            3060
#define INCLUDE_COMBO                   3061
#define RIGHT_PASTE_CHECK               3062
#define EXCLUDE_COMBO                   3063
#define FILTER_CHECK                    3064
#define HELP_CONFIRM_BUTTON             3065
#define SPEED_CHECK                     3066
#define ACL_CHECK                       3067
#define STREAM_CHECK                    3068
#define OWDEL_CHECK                     3069
#define ATONCE_BUTTON                   3070
#define LIST_BUTTON                     3071
#define BUF_STATIC                      3072
#define INC_STATIC                      3073
#define EXC_STATIC                      3074
#define VERIFY_CHECK                    3075
#define EMPTYDIR_CHECK                  3076
#define FORCESTART_CHECK                3077
#define ABOUT_STATIC                    3078
#define NSA_CHECK                       3079
#define MOVEATTR_CHECK                  3080
#define SERIALMOVE_CHECK                3081
#define JOB_COMBO                       3082
#define EXTENDFILTER_CHECK              3083
#define DELDIR_CHECK                    3084
#define JOBTITLE_STATIC                 3085
#define JOB_STATIC                      3086
#define JOBDEL_BUTTON                   3087
#define SPEED_STATIC                    3088
#define AUTOSLOW_CHECK                  3089
#define AUTOSLOW_STATIC                 3090
#define AUTOSLOWIO_CHECK                3091
#define SPEED_SLIDER                    3103
#define REPARSE_CHECK                   3104
#define RUNAS_BUTTON                    3105
#define SERIALVERIFYMOVE_CHECK          3106
#define MAIN_LISTVIEW                   3107
#define MAIN_LIST                       3109
#define READOSBUF_CHECK                 3110
#define NOCONFIRMDEL_CHECK              3116
#define NOCONFIRM_CHECK                 3118
#define TITLE_COMBO                     3123
#define DEL_BUTTON                      3124
#define SOUND_EDIT                      3125
#define SOUND_BUTTON                    3126
#define CMD_EDIT                        3127
#define CMD_BUTTON                      3128
#define SHUTDOWN_CHECK                  3129
#define SHUTDOWNTIME_EDIT               3130
#define FORCESHUTDOWN_CHECK             3131
#define ADD_BUTTON                      3132
#define CMDERR_CHECK                    3133
#define SHUTDOWNERR_CHECK               3134
#define SOUNDERR_CHECK                  3135
#define WAITCMD_CHECK                   3137
#define FORCE_CHECK                     3141
#define SUSPEND_CHECK                   3142
#define HIBERNATE_CHECK                 3143
#define PLAY_BUTTON                     3144
#define FROMDATE_STATIC                 3149
#define TODATE_STATIC                   3150
#define TODATE_COMBO                    3151
#define MAXSIZE_COMBO                   3152
#define MINSIZE_STATIC                  3153
#define FROMDATE_COMBO                  3154
#define MINSIZE_COMBO                   3155
#define MAXSIZE_STATIC                  3156
#define DST_STATIC                      3157
#define DRIVEMAP_EDIT                   3158
#define FILESELECT_BUTTON               3335
#define DIRSELECT_BUTTON                3336
#define MKDIR_BUTTON                    3380
#define RMDIR_BUTTON                    3381
#define FACMD_COMBO                     3382
#define FASTCOPY_ICON                   4000
#define FASTCOPY2_ICON                  4001
#define FASTCOPY3_ICON                  4002
#define FASTCOPY4_ICON                  4003
#define FCWAIT_ICON                     4004
#define JOBOBJ_MENUITEM_START           5000
#define JOBOBJ_MENUITEM_END             5999
#define FINACT_MENUITEM_START           6000
#define FINACT_MENUITEM_END             6999
#define MAIN_MENU                       7000
#define MAIN_RUNAS_MENU                 8001
#define IDR_ACCEL                       9000
#define CLOSE_MENUITEM                  30003
#define SETUP_MENUITEM                  30004
#define HELP_MENUITEM                   30006
#define ABOUT_MENUITEM                  30007
#define SHELLEXT_MENUITEM               30008
#define OPENDIR_MENUITEM                30009
#define FASTCOPYURL_MENUITEM            30010
#define JOB_MENUITEM                    30013
#define IDR_DISKMODE                    30014
#define AUTODISK_MENUITEM               30016
#define SAMEDISK_MENUITEM               30017
#define DIFFDISK_MENUITEM               30018
#define USERDIR_MENUITEM                30019
#define ADMIN_MENUITEM                  30021
#define SWAPTARGET_MENUITEM             30022
#define FIXPOS_MENUITEM                 30023
#define FIXSIZE_MENUITEM                30024
#define DEFFINACT_MENUITEM              30025
#define FINACT_MENUITEM                 30026
#define OPENLOG_MENUITEM                30027
#define EXTENDFILTER_MENUITEM           30028
#define IDR_SWAPTARGET                  30029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        500
#define _APS_NEXT_COMMAND_VALUE         30030
#define _APS_NEXT_CONTROL_VALUE         3382
#define _APS_NEXT_SYMED_VALUE           2383
#endif
#endif
